name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: codespell *

  test:
    runs-on: ${{ matrix.os }}
    env:
      PYTEST_ADDOPTS: "--color=yes"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.13"]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      # TODO: Remove this
      - name: Install pak
        run: pip install git+https://github.com/friedkeenan/pak.py

      - name: Install caseus
        run: pip install .[tests]

      - name: Run tests
        run: pytest

